from __future__ import annotations

import argparse
import csv
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import cv2


IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


@dataclass(frozen=True)
class IssueRow:
    image: str
    gt: int
    pred: int
    matched: int
    false_positive: int
    false_negative: int
    oversized: int
    avg_iou: str

    @property
    def issue_score(self) -> int:
        return self.false_positive + self.false_negative + self.oversized

    @property
    def issue_reason(self) -> str:
        reasons = []
        if self.false_negative:
            reasons.append(f"漏检{self.false_negative}")
        if self.false_positive:
            reasons.append(f"误检{self.false_positive}")
        if self.oversized:
            reasons.append(f"框偏大{self.oversized}")
        return "、".join(reasons) if reasons else "无"


@dataclass(frozen=True)
class YoloBox:
    cls: int
    cx: float
    cy: float
    w: float
    h: float
    conf: Optional[float] = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Collect YOLO evaluation issue samples for review.")
    parser.add_argument(
        "--analysis-csv",
        default="runs_yolo_eval/pipe_yolov8n_eval_predict/analysis.csv",
        help="CSV generated by analyze_yolo_eval.py.",
    )
    parser.add_argument("--dataset-root", default="datasets/pipe_yolo", help="Prepared YOLO dataset root.")
    parser.add_argument("--split", choices=("train", "val"), default="val")
    parser.add_argument("--images-dir", help="Override dataset image directory.")
    parser.add_argument("--labels-dir", help="Override ground-truth label directory.")
    parser.add_argument(
        "--pred-labels",
        default="runs_yolo_eval/pipe_yolov8n_eval_predict/labels",
        help="Prediction label directory.",
    )
    parser.add_argument(
        "--output-dir",
        default="runs_yolo_eval/pipe_yolov8n_eval_predict/issue_samples",
        help="Output review directory.",
    )
    parser.add_argument("--max-count", type=int, default=80, help="Max issue images to collect.")
    parser.add_argument("--preview", action="store_true", help="Generate GT/prediction preview images.")
    parser.add_argument("--clean", action="store_true", help="Remove old output directory first.")
    return parser.parse_args()


def parse_int(row: dict[str, str], field: str, path: Path, line_number: int) -> int:
    try:
        return int(row[field])
    except (KeyError, ValueError) as exc:
        raise RuntimeError(f"{path}:{line_number} 字段 {field} 不是整数。") from exc


def read_issue_rows(path: Path) -> list[IssueRow]:
    if not path.exists():
        raise RuntimeError(f"分析 CSV 不存在：{path}")
    rows: list[IssueRow] = []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        required = {"image", "gt", "pred", "matched", "false_positive", "false_negative", "oversized", "avg_iou"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise RuntimeError(f"{path} 缺少字段：{', '.join(sorted(missing))}")
        for line_number, row in enumerate(reader, start=2):
            item = IssueRow(
                image=(row.get("image") or "").strip(),
                gt=parse_int(row, "gt", path, line_number),
                pred=parse_int(row, "pred", path, line_number),
                matched=parse_int(row, "matched", path, line_number),
                false_positive=parse_int(row, "false_positive", path, line_number),
                false_negative=parse_int(row, "false_negative", path, line_number),
                oversized=parse_int(row, "oversized", path, line_number),
                avg_iou=(row.get("avg_iou") or "").strip(),
            )
            if item.image and item.issue_score > 0:
                rows.append(item)
    rows.sort(key=lambda item: (item.issue_score, item.false_negative, item.false_positive), reverse=True)
    return rows


def find_image(images_dir: Path, stem: str) -> Optional[Path]:
    for suffix in IMAGE_SUFFIXES:
        candidate = images_dir / f"{stem}{suffix}"
        if candidate.exists():
            return candidate
    return None


def read_yolo_boxes(path: Path) -> list[YoloBox]:
    if not path.exists():
        return []
    boxes: list[YoloBox] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) not in (5, 6):
            raise RuntimeError(f"{path}:{line_number} YOLO 标签列数应为 5 或 6，实际为 {len(parts)}。")
        try:
            cls = int(float(parts[0]))
            cx = float(parts[1])
            cy = float(parts[2])
            width = float(parts[3])
            height = float(parts[4])
            conf = float(parts[5]) if len(parts) == 6 else None
        except ValueError as exc:
            raise RuntimeError(f"{path}:{line_number} YOLO 标签字段不是数字：{line}") from exc
        boxes.append(
            YoloBox(
                cls=cls,
                cx=cx,
                cy=cy,
                w=width,
                h=height,
                conf=conf,
            )
        )
    return boxes


def draw_boxes(image_path: Path, gt_label: Path, pred_label: Path, output_path: Path) -> bool:
    image = cv2.imread(str(image_path))
    if image is None:
        return False
    h, w = image.shape[:2]
    preview = image.copy()
    for box in read_yolo_boxes(gt_label):
        draw_yolo_box(preview, box, w, h, (0, 220, 0), "GT")
    for box in read_yolo_boxes(pred_label):
        label = "P" if box.conf is None else f"P {box.conf:.2f}"
        draw_yolo_box(preview, box, w, h, (0, 0, 255), label)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    return bool(cv2.imwrite(str(output_path), preview))


def draw_yolo_box(image, box: YoloBox, image_width: int, image_height: int, color: tuple[int, int, int], label: str) -> None:
    x1 = int(round((box.cx - box.w / 2.0) * image_width))
    y1 = int(round((box.cy - box.h / 2.0) * image_height))
    x2 = int(round((box.cx + box.w / 2.0) * image_width))
    y2 = int(round((box.cy + box.h / 2.0) * image_height))
    x1 = max(0, min(image_width - 1, x1))
    y1 = max(0, min(image_height - 1, y1))
    x2 = max(0, min(image_width - 1, x2))
    y2 = max(0, min(image_height - 1, y2))
    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
    cv2.putText(image, label, (x1, max(18, y1 - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2, cv2.LINE_AA)


def copy_optional(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if source.exists():
        shutil.copy2(source, destination)
    else:
        destination.write_text("", encoding="utf-8")


def clean_generated_outputs(output_dir: Path) -> None:
    output_root = output_dir.resolve()
    for relative_path in ("images", "labels_gt", "labels_pred", "previews"):
        target = (output_dir / relative_path).resolve()
        if output_root not in target.parents:
            raise RuntimeError(f"拒绝清理异常路径：{target}")
        if target.exists():
            shutil.rmtree(target)
    summary_csv = output_dir / "issues.csv"
    if summary_csv.exists():
        summary_csv.unlink()


def write_summary(path: Path, rows: list[IssueRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "image",
                "reason",
                "gt",
                "pred",
                "matched",
                "false_positive",
                "false_negative",
                "oversized",
                "avg_iou",
            ],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "image": row.image,
                    "reason": row.issue_reason,
                    "gt": row.gt,
                    "pred": row.pred,
                    "matched": row.matched,
                    "false_positive": row.false_positive,
                    "false_negative": row.false_negative,
                    "oversized": row.oversized,
                    "avg_iou": row.avg_iou,
                }
            )


def main() -> int:
    args = parse_args()
    dataset_root = Path(args.dataset_root)
    images_dir = Path(args.images_dir) if args.images_dir else dataset_root / "images" / args.split
    labels_dir = Path(args.labels_dir) if args.labels_dir else dataset_root / "labels" / args.split
    pred_labels_dir = Path(args.pred_labels)
    output_dir = Path(args.output_dir)

    if args.clean and output_dir.exists():
        try:
            clean_generated_outputs(output_dir)
        except RuntimeError as exc:
            print(f"问题样本收集失败：{exc}")
            return 2

    try:
        issue_rows = read_issue_rows(Path(args.analysis_csv))[: max(0, args.max_count)]
    except RuntimeError as exc:
        print(f"问题样本收集失败：{exc}")
        return 2

    try:
        collected_rows: list[IssueRow] = []
        missing_images = 0
        for row in issue_rows:
            image_path = find_image(images_dir, row.image)
            if image_path is None:
                missing_images += 1
                continue
            image_output = output_dir / "images" / image_path.name
            image_output.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(image_path, image_output)
            gt_label = labels_dir / f"{row.image}.txt"
            pred_label = pred_labels_dir / f"{row.image}.txt"
            copy_optional(gt_label, output_dir / "labels_gt" / f"{row.image}.txt")
            copy_optional(pred_label, output_dir / "labels_pred" / f"{row.image}.txt")
            if args.preview:
                draw_boxes(image_path, gt_label, pred_label, output_dir / "previews" / image_path.name)
            collected_rows.append(row)
    except RuntimeError as exc:
        print(f"问题样本收集失败：{exc}")
        return 2

    write_summary(output_dir / "issues.csv", collected_rows)
    print(f"问题样本输出目录：{output_dir}")
    print(f"问题图片数：{len(issue_rows)}，已收集：{len(collected_rows)}，缺失图片：{missing_images}")
    print(f"汇总 CSV：{output_dir / 'issues.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
